# Generated by Django 5.1.1 on 2024-10-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_subject_remove_user_following_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
