# Generated by Django 5.1.1 on 2024-10-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_progress_progress_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(max_length=200),
        ),
    ]
